language: objective-c
osx_image: xcode9.1

script:
- xcodebuild clean build test -project "SwiftJson.xcodeproj" -scheme SwiftJson -sdk iphonesimulator11.1 -destination "platform=iOS Simulator,name=iPhone 7,OS=11.1" ONLY_ACTIVE_ARCH=YES
